### ISSUE TITLE
SearchTableAction: Enable searching on icon click

### ISSUE THREAD

**Issue by saifbadran9** [DominoKit/domino-ui#110]
Can we disable triggering search on key change in search field, instead enable it only when clicking the search icon in the SearchTableAction Plugin?

**Comment by vegegoku** [comment]
We will change this to be configurable with a flag to enable auto search or not.

**Comment by vegegoku** [comment]
i think even in auto search we need to have a delay while typing before triggering the search , i will ass that too.

**Comment by saifbadran9** [comment]
Exactly, that might help in case of hitting the server for filtering the data 👍

**Comment by vegegoku** [comment]
In order to turn the auto search of use `setAutoSearch(false)` the user can then trigger the search by hitting the `Enter` key of clicking the search icon, also he can clear the text box by clicking the new clear icon.
auto search delay can now be configured using `setAutoSearchDelay(delayInMillies)`
even with the auto search is on, user still can trigger the search using the enter key or icon click.
