### ISSUE TITLE
Method call order

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#177]
When I call setAttribute method last in chain of method calls on element, previous methods have no effect.
Since nobody understands 1st sentence, here's the code :)

```java
FlexLayout flex = FlexLayout.create().setAttribute("style", "margin-bottom: 200px").setJustifyContent(FlexJustifyContent.CENTER);
```
generates HTML:
```html
<div class="flex-layout" domino-uuid="elemento-uid-2374" style="margin-bottom: 200px; justify-content: center;">
````
So i have both margin-bottom and justify-content properties.

But,
```java
FlexLayout flex = FlexLayout.create().setJustifyContent(FlexJustifyContent.CENTER).setAttribute("style", "margin-bottom: 200px");
```
generates HTML:
```html
<div class="flex-layout" domino-uuid="elemento-uid-2374" style="margin-bottom: 200px">
```
Only property set by setAttribute method (margin-bottom) and justify-content is gone.
It is not FlexLayout related, I noticed this on other elements when using setAttribute("style", "...").

**Comment by vegegoku** [comment]
@doctorj this is an expected behavior set `.setAttribute("style","some style value")` will override the whole style attribute of the element in regards of what ever value it has before the call, while domino-ui methods instead add to the style instead of overriding the value.

With that said i think even domino-ui method should try to add style classes instead of manipulating the element style attribute to avoid such case.

**Comment by vegegoku** [comment]
please feel free to report any component that has the same issue.
