### ISSUE TITLE
Problem with the Tree ActiveItem

### ISSUE THREAD

**Issue by joseprimo3635** [DominoKit/domino-ui#221]
I have the following problem with the Tree
I can not disable the last selection of sub-elements of a tree.

i think the problem is on TreeItem

anchorElement.addEventListener("click", evt -> {
            if (isParent()) {
                collapsible.toggleDisplay();
            }
            parent.setActiveItem(TreeItem.this);
        });

**Comment by vegegoku** [comment]
@joseprimo3635 
The `getActiveItem` should work as expected now.
and you can also use the `getActiveItem` and `getParent` to traverse the Tree, also we added the following new methods :

in the `Tree` class you have : 

- `getActivePath` : will return a list of TreeItem of the current active path of the tree.
- `getActivePathValues` : the same but returns the values instead of the TreeItem.

in the `TreeItem` class

- `getPath` : returns a list of TreeItem that represent the path of the TreeItem from the root tree.
- `getPathValues` : the same but return the values instead of the TreeItems.
