### ISSUE TITLE
[Form fields] Form elements inside table make rows too high

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#307]
Since form elements have padding-top set, using TextHeaderFilter, SelectHeaderFilter, DateHeaderFilter makes table header filter row too high.
Not only table header, the same goes for table rows if there are form fields inside.

**Comment by vegegoku** [comment]
The issue for Header filters is fixed on branch 
https://github.com/DominoKit/domino-ui/tree/form-fields-revamped

will work on fixing this for normal table rows, but then there will be some assumptions for some method to be called to make the fields fit inside the table row.

**Comment by vegegoku** [comment]
now adding fields directly into the table cell well fit the field and condense the view, otherwise if the field is not a direct descendant of the `td` element you can call `asTableField` on the field to make it fit in the cell as if it was directly inserted into the cell.

this is useful to make sure that we can customize the behavior and allow variant alternatives.

![image](https://user-images.githubusercontent.com/5379625/69965622-5acf6e80-151d-11ea-8a0a-e2a60ee0f785.png)
