### ISSUE TITLE
Introduce a getValue method for a DataTable cell

### ISSUE THREAD

**Issue by HMIDeer** [DominoKit/domino-ui#343]
**Is your feature request related to a problem? Please describe.**
Currently it isn't possible to the value of a cell renderer inside a DataTable

**Describe the solution you'd like**
Introduce a getValue method for a cell which a CellRenderer can implement

**Comment by vegegoku** [comment]
Because the cell could contain any kind of element and could provide any kind of value, it would be hard to tie the cell with a specific data type and it will bring complexity to the implementation and the use of the datatable, so instead i am thinking of the following approach :

Dirty record approach:
=====================

in such approach the user can define a dirty record provider which will be used to create a new record when ever we ask for the edited value of the row: e.g

```java
tableConfig.setDirtyRecordProvider(originalRecord -> //create a dirty record, default will return the same record);
```

then each cell can operate on that record by implementing a function, e.g `onDirtyRecordUpdate(OriginalRecord, DirtyRecord)`
the default will return the dirtyRecord.

now in your code you can update the dirty record from within the cell renderer
.
