### ISSUE TITLE
Enhance Select element to add new values created by a user

### ISSUE THREAD

**Issue by G3rmanW1ng** [DominoKit/domino-ui#350]
**Is your feature request related to a problem? Please describe.**
A user should select values but in some cases the user should have the ability to add additional values.

**Describe the solution you'd like**
Enhance Select element to add new values created by a user. Parse the user input and create a select option if valid.

**Describe alternatives you've considered**
Currently nothing, maybe there is another solution

**Comment by HMIDeer** [comment]
@vegegoku Have you already thought about this idea?

**Comment by vegegoku** [comment]
@HMIDeer yes i did, and this feature which i would love to add has a conflict with another feature, which will allow the user to select the first option in the search, i mean when the user type part of an option then hit enter it will select the first option, so now what if he is actually -after we add this feature- wants to add a new option not select existing one?!

i could think of few options here :

- Add an option to select which behavior to use when the user hits the `Enter` key.

or

- If the this feature is enabled, then only add new value if there is no matching results.

or

- Allow the add option with a different key combination or  (mouse click which might not be a good option IMHO).

so i am still open to this, bringing this as a discussion in the channel would be good idea, WDYT?

**Comment by HMIDeer** [comment]
Discussing this in the channel would be a good idea. For me the configurable behavior sounds like a sensible solution. The approach with a different key combination or mouse click wouldn't work for mobile devices I guess. Although a combination of both functions would be nice there would be a problem if a user wants to enter a value e.g. of AB but there is already ABC in the select. Instead of adding AB, ABC gets selected.

**Comment by NickGaens** [comment]
> If the this feature is enabled, then only add new value if there is no matching results.

The severe downside of this option would be that if a user wants to add a new option from the very start, he/she would have to know to start typing until no more options are available before having the ability to add a new one.

My suggestion would be to

    1. add a flag to Select (something like 'showCustomOptionInput' or so).
    2. add an input field and a subtle horizontal separator on top of the list of options, if the beforementioned flag is enabled. The user will have to hit the enter or return key for the item to be selected + added to the list of pre-existing options. It might be beneficiary to add some sort of customizable 'Ok'-button right next to the input field to provide a secondary way of confirming the input.

**Comment by mamta** [comment]
I think Enter is ideal for selection. In case of conflict, manual selection can be offered. 

In the below link, three types of comboboxes are showed, manual and automatic selection -
https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

**Comment by rdeangelis83** [comment]
Hi I like the solution of atlaskit by Atlassian: https://atlaskit.atlassian.com/packages/core/select
See the last example "Creatable Select"

**Comment by HMIDeer** [comment]
> 
> 
> Hi I like the solution of atlaskit by Atlassian: https://atlaskit.atlassian.com/packages/core/select
> See the last example "Creatable Select". They simply offer an additional entry to create a new option.

Never seen such a solution. But thats a great idea!

**Comment by NickGaens** [comment]
I must concur with @rdeangelis83 and @HMIDeer: Atlassian's Select does seem great.

**Comment by vegegoku** [comment]
@rdeangelis83 very nice :+1: , i will implement it like that.

**Comment by rdeangelis83** [comment]
> @rdeangelis83 very nice 👍 , i will implement it like that.

I'm not sure whether it would be better to place the "create" new option item as first option in the item menu instead of to place it on the end? But this is really a small detail ...

**Comment by vegegoku** [comment]
@rdeangelis83 this idea does not actually fix the conflict between select first element on enter or create a new option without making the user take an extra action, but i like the idea as it make more sense than other options and should work fine with both mobile and desktop.

**Comment by HMIDeer** [comment]
Any updates on this? Anything I can help with?

**Comment by vegegoku** [comment]
Based on the discussions we had on the issue we need to consider a few things here : 

- The behavior of default selecting the first element found.
- The ability to create new elements even if there are elements found.

My vision on this could be something like this

![image](https://user-images.githubusercontent.com/5379625/98919636-bcdb7680-24d7-11eb-9de5-a84ea7283571.png)

- If the Select is creatable we will add a button next to the search element.
- The create button will only be active when the search field has a value.
- The user can create and add a new element by click on the add button at any time or by press the tab to focus on the button then enter.
- Pressing enter on the search field will only select the first found option if exists.
- We do not assume we are adding strings, the select field can have a generic value which means we need to register some kind of addOptionHandler for which we pass the value from the search element and returns a SelectOption that if exists we append to the select. so It could return and optional. (also this can be used if the user wants to actually persist the new option somewhere)
- When we add a new option and after we append it we auto select that option.

**Comment by HMIDeer** [comment]
In our discussion at the beginning of the year @rdeangelis83 pointed to the Creatable select from atlasian and we agreed that this would be a proper solution. In that case i've tried to implement it like that with https://github.com/DominoKit/domino-ui/pull/502

![grafik](https://user-images.githubusercontent.com/48472935/98922886-49d00100-24d3-11eb-8f3e-128d8301dd64.png)
![grafik](https://user-images.githubusercontent.com/48472935/98922983-63714880-24d3-11eb-9aea-05be977d1593.png)

- If the Select is creatable instead of "No result found" "Create..." is displayed, since for my opinion it isn't really necessary to have a "No result found" in case the select is creatable since "Create ..." only appears if no entry has been found. 

- The user is able to create a new element by click on "Create ..." or by changing the focus to it with tab and press enter afterwards.

The other points you mentioned are also working and I completly agree with the generic value and the handler thats why I've implemented that CreationHandler which gives the developer the possibility to decide how the SelectOption should be created or check if the input is valid.

**Comment by vegegoku** [comment]
Yes, my comment was based on the accumulated information we got from the discussion and from my observations of how we can maintain all features without sacrificing any.

I think the implementation I described above will solve all issues, it will be good for both desktop and mobile users, also mouse and keyboard users.

we still are using the select first found result while we also still can add a new entry. and we also still have no result found indicator.

**Comment by HMIDeer** [comment]
So you think the Creatable select isn't able to maintain all features without sacrificing any. The only thing is the no results indicator but if this really necessary we could also add the text No results found, create xxx?

**Comment by vegegoku** [comment]
No, what i mean, in the PR for example you can only add if you have no result found, but what if I found 2 result but I still want to add a new one anyway?

now this in mind what if you want to select the first result but not add a new one?

the approach with the button as in the attached image should retain all features without any conflict.

**Comment by HMIDeer** [comment]
Ok so in that case we need something like that.

![grafik](https://user-images.githubusercontent.com/48472935/98932097-2e6af300-24df-11eb-8121-eb17bf7c047e.png)

But you are right, thats something which is currently missing at the PR

**Comment by vegegoku** [comment]
But not as an 'Create "abc" ' option in the drop down, we need a button next to the search text input, since we can add while we have results it will be down below and will require a lot of key press to reach, a button next to the search will be reached with a single tab then enter to add the new option

**Comment by HMIDeer** [comment]
Ok, I personally would prefer a solution without a additional button. But its your project so thats up to you. In that case I'll delete the PR since it goes completly in the wrong direction.
