### ISSUE TITLE
TimeBox issue with specific Date values

### ISSUE THREAD

**Issue by HMIDeer** [DominoKit/domino-ui#378]
**Describe the bug**
Using a TimeBox and setting a value where jsDate.getHours() is 0 the exception "Cannot read property 'getCircle_0_g$' of null" is thrown. 

**To Reproduce**
1. Create TimeBox
2. Set a date value where the date has a hour value of 0
3. The exception is thrown

**Expected behavior**
The time value is displayed.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 80.0.3987.132

**Smartphone (please complete the following information):**
-

**Additional context**
-TimePicker hourElements map didn't contain a element for 0

**Comment by vegegoku** [comment]
Is it possible that you are using 12hours clock with 24hours value, notice that for time when you use 12hours formats the hours are calculated from 1 to 12 while for a 24hours clock the hours are calculated from 0 - 23.

so can you try to set the time box style to 24hours and test

**Comment by HMIDeer** [comment]
You are right, i've tested it with both clock styles. With 24 it working with 12 not. But what about if we want to use the 12 hours format e.g. dependent of the browser language because normally in the US the 12 hour format is used while in Europe 24 is familiar. I think the TimeBox should handle both cases.

**Comment by vegegoku** [comment]
I think this should be handled by the application, because if you set the field value with a specific date how would the field tell that it was in 12 or 24 hours format, of course if the hours are greater than 12 then it is obvious, but what about values from 1-12, are they 12 or 24? we need to notice here that this kind of format is about presentation and not actually reflected into the actual value.

and the answer for your comment below is that you can check for the user browser locale and accordingly decide how to create the time box, then for the API from where you get the date or time you convert it to match the locale.

**Comment by HMIDeer** [comment]
I think my issue description isn't really clear enough. What I want to say is that if i print out the date values of my java.util.Date object using getHour and getMinutes the value for 12am which is 0h and 0m but it won't get rendered if i am calling the value method of the TimeBox with this Date object. For my opinion 12am should be displayed for that. Additionaly if i am having a value which can be rendered and setting 12am manually at the the TimePicker it will be transfered to 12pm using a changehandler but getting rendered as 12am in the field itself.

With the localization thing I completly agree.

**Comment by vegegoku** [comment]
Can you show me a sample code of what you are doing and how you print it, as i think again, once the value is converted to Date there is no AM PM in there it is just a long, AM/PM is a thing for formatting - or you did for printing - what you set in the timebox is the `Date ` value not the string of that date value, which can be presented by both formats, and there is no way that the timebox can tell which format is correct. since both are correct.

**Comment by HMIDeer** [comment]
Date value = new Date(2020, 3, 11, 2, 0, 0);

        GWT.log(Integer.toString(value.getHours()));
        GWT.log(Integer.toString(value.getMinutes()));
        GWT.log(Integer.toString(value.getSeconds()));

        TimeBox timeBox = TimeBox.create();
        timeBox.value(value);

        timeBox.addChangeHandler((Date d) -> {

            GWT.log(Integer.toString(d.getHours()));
            GWT.log(Integer.toString(d.getMinutes()));
            GWT.log(Integer.toString(d.getSeconds()));
            
        });

**Comment by HMIDeer** [comment]
> 
> 
> `Date value = new Date(2020, 3, 11, 2, 0, 0);
> GWT.log(Integer.toString(value.getHours()));
> GWT.log(Integer.toString(value.getMinutes()));
> GWT.log(Integer.toString(value.getSeconds()));
> 
> ```
>     TimeBox timeBox = TimeBox.create();
>     timeBox.value(value);
> 
>     timeBox.addChangeHandler((Date d) -> {
> 
>         GWT.log(Integer.toString(d.getHours()));
>         GWT.log(Integer.toString(d.getMinutes()));
>         GWT.log(Integer.toString(d.getSeconds()));
>         
>     });`
> ```

**Comment by HMIDeer** [comment]
Missclick sorry
