### ISSUE TITLE
Support GWT-2.9.0 and Elemental-1.1.0

### ISSUE THREAD

**Issue by Oberonc** [DominoKit/domino-ui#518]
I didn't see any road map or official issue about this matter, so I figured I might as well open one.

**Comment by vegegoku** [comment]
We are already working on this, DominoKit has several libs and frameworks and we are doing this in order of dependency ..since some of those depend on each other we have already released few modules as you can see here https://search.maven.org/search?q=org.dominokit

and we are working on the remaining modules.

the release process includes migration to gwt 2.9 and latest elemental2-1.1.0 plus writing some java-docs and enhance the releasing process for future releases.
