### ISSUE TITLE
Card header not visible if create with not title using create()  and then setTitle() is used

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-ui#545]
**Describe the bug**
* Create a card using `Card card = Card.create();`.
* Add  `card.setTitle("test");`

The header of the card is not visible. Now try:

* Create a card using `Card card = Card.create("");`.
* Add  `card.setTitle("test");`

The header is visible.

**Expected behavior**
`setTitle`shpuldmak the header visible also in cases whreer the card is created using `create()`.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 1.0.0-RC3

**Additional context**
The easeiest solution would be to add `this.setHeaderVisible(true)` inside the `setTitle`-method. If you agree, I can do a PR.

**Comment by vegegoku** [comment]
This seems to be a little bit more complicated .. since now we can have and icon on the left with title and some actions on the right..so we should count for any of those if it is added we should show the header anyway .

Now if the title is empty or null it does not mean we should hide the header unless there is nothing else added.

If you think can make PR to fix it with this in mind that is appreciated.

**Comment by FrankHossfeld** [comment]
Yes you are right. We need to do that in all other places, too.
