### ISSUE TITLE
ScrollingPagination updatePagesByTotalCount = 0

### ISSUE THREAD

**Issue by happyhua** [DominoKit/domino-ui#603]
When you call `updatePagesByTotalCount = 0` to a `ScrollingPagination`, the corresponding `pageChangedCallBack` will never been invoked.

I am not sure if it is better to fire a page changed event with a page index like -1 or 0.

Besides it, the code in `moveToPage` like `nextElement.disable();` will also NOT be invoked due to the `if (page > 0 && page <= pagesCount)` check. Effectively it leaves some arrows by an empty page, maybe it is better to hide them by an empty pagination?

**Comment by happyhua** [comment]
An other option is providing an hide api on Pagination, to hide entire Pagination.
It can either automatically being invoked when total count is set to 0 or user should call it by himself.

Just some ideas, I am self not sure what the best approaching is.

**Comment by vegegoku** [comment]
> An other option is providing an hide api on Pagination, to hide entire Pagination. It can either automatically being invoked when total count is set to 0 or user should call it by himself.
> 
> Just some ideas, I am self not sure what the best approaching is.

IMO we need to fix the total pages 0, then about the hiding we also fix the bug but I dont think we need to hide the pagination entirely, this might lead to weird UI behavior and force everyone to workaround them, the manual hide is already there, the pagination is a DominoElement that implement the function.

**Comment by vegegoku** [comment]
ok so lets get them 1 by 1

**Should we call it with page**  -1 or 0

according to this code
```java

    if (pages > 0) {
      moveToPage(1, true);
    }

    if (pages <= 0) {
      nextElement.disable();
      prevElement.disable();
    }
 ```
pagination always starts from 1 so it make sense to call it with 0 not -1.

**pageChangedCallback not being fired for pages count = 0 **

It is actually not calling page changed for any count not just 0 

```java
    if (pages > 0) {
      moveToPage(1, true);
    }
```
The true in this code goes for the silent flag, which then used to avoid triggering the handlers

```java
      if (!silent) {
        pageChangedCallBack.onPageChanged(page);
      }
```
Why is this? if we follow out the logical order of how we might used the pagination, normally we will do a request with default page number and page size but we wont know the total pages count until we receive the results and only then we actually update the pagination with total counts, and we dont want that to trigger a new request since we already know on which page we are.
If we dont avoid calling the callback we will be doing the request twice.

With that said, I think there might be different cases where we might trigger the first request by actually updating the pagination, so there should be an option to do so, which simply by allow passing that silent flag with a default value to true.

**Comment by vegegoku** [comment]
with the fix we can now trigger the pageChangeCallback with update total count and update pages by passing the silent flag.
also the navigation arrows issue should be fixed when total count is 0
