### ISSUE TITLE
Odd/Unexpected Responsive Behavior with Window

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#666]
**Describe the bug**
When resizing the browser, it changes the Window size in unexpected ways; including resizing the Window to go off screen.

**To Reproduce**

Use this small bit of code:
```java
Window.create("Test Window")
        .setSize(ModalSize.SMALL)
        .appendChild(Select.create("Test Select")
            .appendChild(SelectOption.create(0, "--select--"))
            .appendChild(SelectOption.create(10, "10"))
            .appendChild(SelectOption.create(20, "20"))
            .appendChild(SelectOption.create(30, "30"))
            .appendChild(SelectOption.create(40, "40"))
        )
        .open();
```
1. Position the Window near the center of the client
2. Resize browser width
3. See error

**Expected behavior**
It would be expected that the Window stays within the bounds of the browser client area when resizing the browser

**Screenshots**

![Jun-16-2022 09-25-57](https://user-images.githubusercontent.com/861908/174083140-1459f756-3ae0-4bc1-8c29-0f8c6d80afd1.gif)

**Comment by vegegoku** [comment]
It seems this happens when switching to small screens media,  what happens normally with dialog is that for small screen they always have the same width, despite the actual size settings since it makes not sense to have ultra small dialog on an already small screen. so instead they take almost the screen width, but a dialog is centered by default while a window can move around and have a fixed position, so it stretch but does not move correctly to the center of the screen.

the correct fix for this would be to center the window when it is stretched due to screen size become too small.

**Comment by vegegoku** [comment]
I pushed a fix for this that aligns with my last comment, I will leave this open for sometime to get more feedback on this.
