### ISSUE TITLE
Tree Grid for large data sets

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#691]
I have a use-case that needs a Tree grid for large data sets.   Currently, it appears that all nodes for a tree grid are in DOM, even for leaf nodes that are hidden due to parent/ancestor being collapsed.   If the tree grid has several columns and 5000+ nodes, the performance in the browser with that many DOM elements will suffer.

This request is to either update the tree grid plugin to support sparse rendering or some other mechanism to support only  rendering of elements that are visible to the user rather than 1000's of hidden nodes.

**Comment by vegegoku** [comment]
The plugin configuration have been updated to provide a lazy flag, when this flag is set to true the tree gird will only load and render the child records when the user expand that row, but with this since there is no way to know if there is actually child records, the branch rows will always show the expand icon, once it is expanded the icon will be changed to indicate a leaf or a branch row based on having child records or not.
