### ISSUE TITLE
Disabled SearchBox is still interactive 

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#742]
A SearchBox that is disabled should not receive tab focus and not be interactive.

If I create a simple structure:
```java
TextBox.create()
SearchBox.create().disabled()
TextBox.create()
```

I can focus on the first TextBox and tab into the SearchBox even though it's disabled.

**Comment by jhickman** [comment]
Was thinking of a more 'global' approach to this.. maybe something that works with any element.     Basically being able to add a capture event handler for focus; and that event listener will stopImmediatePropagation and then also blur the event target?    That seems to work for me locally.   Not completely finished, but here's a small utility I made:

![image](https://user-images.githubusercontent.com/861908/209185089-e72ecc86-b238-4e35-82a8-9d00e5803e6c.png)

**Comment by jhickman** [comment]
The reason I created the utility is because other components can make use of it, such as the DataTable.  even if DataTable is disabled, any inline focusable components inside of the table are still fair game... Such as inline cell editors, etc

**Comment by vegegoku** [comment]
according to MDN those are the interactive content by default 
https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#interactive_content

those elements can receive focus by default plus any element that have a tabindex >= 0

I tested with the utility above, but then I needed 3 more tab key press to actually reach the 2nd enabled textbox, added another disabled search box and needed another 3 tabs (total of 6) to reach the 2nd enabled text box, this is because the Searchbox has one focusable field (The text input ) and 2 icons with tabindex the search icon and the clear icon.

I was thinking with a utility that can actually get all focusable elements and all elements with a tab index within the target element and disable them.

**Comment by vegegoku** [comment]
I added a new utility that  can disable any element with its children, the utility will respect the original child element disable state, and there will be no required extra tabs to jump to the next focusable none disabled element, also this can be used to disable a set of elements wrapped by a parent, for example disabling a div that wraps a set of form fields will also disable all those form fields. enable works the same.
