### ISSUE TITLE
zindex issues with Layout

### ISSUE THREAD

**Issue by e-altintas** [DominoKit/domino-ui#758]
When the ZIndexListener of Layout activates, it can put the Layout over the modals and the modal backdrop.

1. Have a Layout and open a modal
2. Have an element in your modal that implements IsPopup (ex Select because the DropDownDown menu inside implements it, or DateBox)
3. Open this element
4. ZIndexListener of the Layout activates, and puts the Layout over the modal and modal backdrop

I don't know what justify the need of this specific listener in the Layout, but it was introduce to fix this bug : https://github.com/DominoKit/domino-ui/issues/690

**Comment by vegegoku** [comment]
@e-altintas Can you please specify the version you are using?

**Comment by vegegoku** [comment]
Ok I guess I managed to to reproduce this.

As for the justification, in order to make the z-index actually work specially when domino-ui components are used with other UI libraries we need to implement the z-index to be dynamic,  and the current implementation will always increment the z-index every time a popup opened, this will make sure that opening a pop from a pop up will always have a higher z-index, but we dont want those popups to be above the layout  when the layout content scrolls, we make sure the z-index of the layout is higher than those pop ups but less than the modals.

In the case of a pop up inside a another we should not do this to avoid this issue..I will provide a fix as soon as possible

**Comment by e-altintas** [comment]
Thank you ! I use the latest version for information
