### ISSUE TITLE
Can't change the icon of a DropdownButton

### ISSUE THREAD

**Issue by e-altintas** [DominoKit/domino-ui#764]
Using the method setIcon on a DropdownButton generates an error.

DropdownButton button = DropdownButton.create(Icons.MDI_ICONS.bell_outline_mdi());
button.setIcon(Icons.MDI_ICONS.bell_ring_outline_mdi());

Error : Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Works fine with the class Button and should work with DropdownButton too

Domino version : RC17

**Comment by e-altintas** [comment]
Works fine if you setIcon to null before setting the new icon

**Comment by salashnik** [comment]
This makes button icon displayed after text by-default, and DropdownButtons displayed without icon (it replaced by caret image)

**Comment by vegegoku** [comment]
The commit also introduced a change that allow you to change the icon position `setIconPosition`, keeping it depending on the order of calling set icon or content is not a good way to handle it.

I am not sure what you mean by `and DropdownButtons displayed without icon (it replaced by caret image)`

**Comment by vegegoku** [comment]
I think now I got it and updated the fix for that part.

**Comment by salashnik** [comment]
This really better ;-) caret displays again ;-)
But why You make default iconOrder right-aligned?
In prev versions icon aligned to left. may be make default button icon position configurable via DominoUIConfig?

**Comment by vegegoku** [comment]
There was no default for Icon order, it was depending on how you create the button - aka based on methods call order - if you create with icon then set content the icon will be on the left, if you create with text the icon on the right, or based on the order of how you call setIcon, setContent, and this was never intended to be correct behavior, and changing how the icon is aligned based on the methods calls is not a good way to do it. for example : You have the impression that Icons are placed on the left by default as you were creating with icon rather than text.

the setIconPosition will make sure the icon position will not change if someone changed the methods call order as part of a refactor.

**Comment by salashnik** [comment]
currently  both buttons look the same - text first, then icon:

```
            .appendChild(Button.createPrimary(MESSAGES.create())
                .setIcon(EuaIcons.create())
            )
            .appendChild(Button.createPrimary(EuaIcons.create())
                .setContent(MESSAGES.create())
            )```

and only if i add `setIconPosition` then displayed correctly
```
            .appendChild(Button.createPrimary(EuaIcons.create())
                    .setContent(MESSAGES.create())
                    .setIconPosition(IconPosition.LEFT)
            )
```
![image](https://user-images.githubusercontent.com/1460514/225138711-f4edbae3-ef03-4f6b-b5bf-addbb20786ff.png)

and as i see in Your code, You have default order:

```
    textContainer = FlexItem.create().setFlexGrow(1).setOrder(20);
    iconContainer = FlexItem.create().setOrder(30);
```
order=30 - is IconPosition.RIGHT ;-)
