### ISSUE TITLE
clickable icon: does not reset state

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-ui#817]
**Describe the bug**
Create a clickable icon using something like this:

```
        Icons.pen()
            .addCss(dui_fg_green)
            .clickable();
```

run the code and click the icon. Every thing works as expected, except that after the click, as long as the focus is on the icon, hte icon stays selected. Please see video:

https://github.com/DominoKit/domino-ui/assets/8287845/543248c2-28dc-4ff3-84b5-07e104dcc48d

Is this a bug or a feature?

Using HEAD-SNAPSHOT of v2.

**Comment by vegegoku** [comment]
There are few states involved here:

1. Hover state : the icon has a grey background.
2. Mouse down state or click state : the wave effect is applied.
3. Focus state : the icon has focus even though the mouse is not within the icons space but it can accept keyboard events.


What you have here after a click is the focus state, so after the click the icon will still has focus and cab still accept keyboard events, so this happens when the click action does not change the focus to a different element in the page, so this is a valid behavior. 

for example you can click then press tab to move to the next focusable element.
