### ISSUE TITLE
Ability to register open/close listeners for side drawers(left | right).

### ISSUE THREAD

**Issue by mP1** [DominoKit/domino-ui#821]
I would like the ability to register listeners for the drawers. As mentioned on gitter im not sure when the open listener should fire, but i guess it should fire when the drawer is fully open after animations have completed. THe same would be true of the close listener.

**Comment by vegegoku** [comment]
As mentioned in the chat support channel, open/close or expand/collapse have been standarized touse CollapseStrategy which already have the ability to register such listeners, there might be some component that might miss that so in that case if reported we will implement the feature in that standard way. for the layout drawers it was different since they dont use that and the animation is controlled with a css class attached/removed from the main layout, in general we added a new utility that is available for domino-ui components to listen to transition events.

check the `TransitionListeners` class, which is already part now of the BaseDominoElement
The user can now use the class like this : 

```java
TransitionListeners.of(element)
                .onTransitionStart(target -> {
                    DomGlobal.console.info("Transition started");
                })
                .onTransitionEnd(target -> {
                    DomGlobal.console.info("Transition Ends");
                })
                .onTransitionCancel(target -> {
                    DomGlobal.console.info("Transition Canceled");
                });
```

or directly on a domino-ui component :

```java
element
                .onTransitionStart(target -> {
                    DomGlobal.console.info("Transition started");
                })
                .onTransitionEnd(target -> {
                    DomGlobal.console.info("Transition Ends");
                })
                .onTransitionCancel(target -> {
                    DomGlobal.console.info("Transition Canceled");
                });
```

The new API is now used to also add open/close listeners for the layout left/right drawers and the handlers can be registered like :

```java
 layout.onLeftDrawerOpen((parent, drawer) -> {
            DomGlobal.console.info(">>::::::::: LEFT Drawer open");
        });

        layout.onLeftDrawerClosed((parent, drawer) -> {
            DomGlobal.console.info("<<::::::::: LEFT Drawer close");
        });

        layout.onRightDrawerOpen((parent, drawer) -> {
            DomGlobal.console.info(">>::::::::: RIGHT Drawer open");
        });

        layout.onRightDrawerClosed((parent, drawer) -> {
            DomGlobal.console.info("<<::::::::: RIGHT Drawer close");
        });
```
