### ISSUE TITLE
v2: Sub-classes of NumberTextBox#getType -> "tel" not "number" *BUG*

### ISSUE THREAD

**Issue by mP1** [DominoKit/domino-ui#825]
The abstract class NumberTextBox#getType returns "tel", none of the sub classes such as IntegerBox etc override, which means they are rendered in Chrome as a telephone text box and not a number.

This means an IntegerBox with min/max/step does not have the up/down decorations etc.

This is also evident in the demo2

https://demo2.dominokit.org/forms/input-fields

<img width="791" alt="image" src="https://github.com/DominoKit/domino-ui/assets/726970/dd6751a9-3ddc-4428-a2c6-0bc1c6f3a97f">

**Comment by mP1** [comment]
Simple fix

```
new IntegerBox() {
   @Override
   public String getType() {
      return "number";
   }
}
```

**Comment by vegegoku** [comment]
There is a good reason for why we do this, since those fields needs to accept formatted values based on different locales and needs to use commas `,` , in many cases we cant use input type number because this means we cant use any kind of a custom value formats, some locale does really use the `,` for example for decimal points and `.` for thousands separators. and there is cases when you need to format numbers with custom patterns that might include other symbols like for example money values with currency symbols. `tel` type is the closest to number that still allow us to do such kind of custom formats.

So here the solution I think is to provide a different set of number inputs that does not include the formatting features, this is the best we can do in this area, WDYT?

**Comment by mP1** [comment]
Perfectly understandable, i guess the only problem i have is the up/down spinners are missing. Perhaps code could be added to "emulate" the native spinners.

**Comment by vegegoku** [comment]
In that case I prefer not to implement the duplicated inputs and suggest using the Postfix elements to simulate the steppers, the step is an attribute and is readble.
