### ISSUE TITLE
DataTable mixed plugins DragAndDrop with Edit mode should disable DragAndDrop

### ISSUE THREAD

**Issue by howudodat** [DominoKit/domino-ui#920]
**Describe the bug**
DataTable with both DragDropPlugin and edit mode, doesn't prevent the drag while in edit mode.

**To Reproduce**
Create DataTable with DragDropPlugin
Edit a row
Click Drag to select text in a textbox

**Expected behavior**
The drag event shouldn't bubble to the Drag plugin when the row is in edit mode;

**Screenshots**
![image](https://github.com/DominoKit/domino-ui/assets/3333605/8af86e01-59f5-4d3e-8d31-851bef68a9ad)

**Comment by vegegoku** [comment]
Instead of disable drag/drop by default in such case which is actually a case that span between different plugins, we introduced new configuration and API to allow working around this while keeping it possible for others who might want  to still drag/drop while in edit mode.

now you can use the following configuration to temporary enable/disable the operation

```java
 tableConfig
     .setOnRowEditHandler(row** -> row.setDraggable(false))
     .setOnRowFinishEditHandler(row -> row.setDraggable(true));
```
