### ISSUE TITLE
Double click tree node, open & close error!

### ISSUE THREAD

**Issue by raindroplvy** [DominoKit/domino-ui#928]

**Comment by raindroplvy** [comment]
Who can help me to solve the problem?

**Comment by niloc132** [comment]
It looks like you forgot to provide what version you're using, a code sample that shows the issue, a description of the issue, or even a screenshot and sentence explaining what the error is?

I cannot see any errors clicking at https://dominokit.com/domino-ui/demo/v1/components/tree using domino-ui v1, nor https://dominokit.com/domino-ui/demo/v2/components/tree for domino-ui v2.

**Comment by raindroplvy** [comment]
When I first double click the tree node, it expand or collapse normally, but next click will got this:
![1715389691950](https://github.com/DominoKit/domino-ui/assets/5383383/38df122b-33f1-48e2-82f1-68dae33313e3)

**Comment by raindroplvy** [comment]
Who can give some advice?

**Comment by niloc132** [comment]
@raindroplvy this is a free, open source project - while paid support is provided, bugs that come in are triaged and fixed when time permits. Check out https://matrix.to/#/#DominoKit_domino:gitter.im for another avenue towards community support, otherwise please be patient until this can be addressed.

And naturally, as an open source tool, you are welcome to take a deeper look and submit a PR if you're able to find a solution.

In the meantime, bumping tickets by adding new comments to get attention isn't constructive.

**Comment by raindroplvy** [comment]
OK, understand. Thanks for your response @niloc132.

**Comment by FrankHossfeld** [comment]
TBH, reading the comments, I am not able to recognize the problem. A more detailed error description is desirable.

**Comment by vegegoku** [comment]
fixed with #984
