### ISSUE TITLE
Slider bubble cuts off text

### ISSUE THREAD

**Issue by howudodat** [DominoKit/domino-ui#968]
**Is your feature request related to a problem? Please describe.**
The thumbnail for the slider cuts off text if it is more than 2 characters.  

**Describe the solution you'd like**
Can we either expand the bubble or automatically shrink the font?

**Describe alternatives you've considered**
Right now I am convertiing the number from 1000 to 1 (ie: 2500 = 2.5)

**Additional context**
![image](https://github.com/user-attachments/assets/691f58c3-6f13-4de5-89e3-26bafeb4f8a6)

**Comment by vegegoku** [comment]
With the fix we can use two different styles for the thumb, the rounded style and the flat style, rounded is the default one which is similar to what we had before the fix and it wont support large text since that wont look good how ever we do it.
flat one will render the thumb in rectangle shape that allow the text to expand as much as needed.

Rounded
![image](https://github.com/user-attachments/assets/b16f3661-5242-4068-b4ce-5f6f5c25adbb)

Flat

![image](https://github.com/user-attachments/assets/2d077260-cdc7-4ca7-88a1-723e234f5ba1)


The default can be change globally using the DominoUiConfig.
